##### Config file #####

sample:
  healthy: "/mnt/projects/huangwt/wgs/hanae/lowtbcfdnabams/NCC_CRC-1014_090516-CW-T-sort.bam"
  tumor: "/mnt/projects/skanderupamj/wgs/data/training/ready.bams/cfdna/NCC_CRC-1014_110116-CW-T-ready.bam"
  buffycoat: "/mnt/projects/skanderupamj/wgs/data/training/ready.bams/cfdna/NCC_CRC-1014_110116-CW-N-ready.bam"

samplename:
  healthy: "CRC-1014_090516"
  tumor: "CRC-1014_110116"
  buffycoat: "CRC-1014_110116-BC"

dilutionfactors: "70-0 70-80 50-100 30-120 20-130 10-140 5-145 70-30 70-130 70-180"

chr: 22

healthydir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/dilutions_series/dilutions_series_chr22/NCC_CRC-1014_090516-CW-T"
tumordir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/dilutions_series/dilutions_series_chr22/NCC_CRC-1014_110116-CW-T"
buffycoatdir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/dilutions_series/dilutions_series_chr22/NCC_CRC-1014_110116-CW-N"
outputfolder: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/dilutions_series/dilutions_series_chr22"

tffile: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/raw_data/ctDNA_burden_estimation_deepwgs_plasma_CRC_samples.csv"
ichorcnaextdata: "/mnt/projects/carriehc/cfDNA/anaconda3/envs/ichorcna/lib/R/library/ichorCNA/extdata/"
