##### Config file #####

sample:
  healthy: "/mnt/projects/skanderupamj/wgs/data/cfdna.crc/cfDNA.20211019/NCC_CRC-123_121115_P/bcbio_work/align/NCC_CRC-123_121115_P-T/NCC_CRC-123_121115_P-T-sort.bam"
  tumor: "/mnt/projects/skanderupamj/wgs/data/cfdna.crc/cfDNA.20211019/NCC_CRC-123_310715_P/bcbio_work/align/NCC_CRC-123_310715_P-T/NCC_CRC-123_310715_P-T-sort.bam"
  buffycoat: "/mnt/projects/skanderupamj/wgs/data/clonal.hema/bams/WHB12842/NCC_CRC-123_070116_P-W-N-sort.bam"

samplename:
  healthy: "CRC-123_121115-CW-T"
  tumor: "CRC-123_310715-CW-T"
  buffycoat: "CRC-123-CW-N"

dilutionfactors: "70-0 70-80 50-100 30-120 20-130 10-140 5-145 70-30 70-130 70-180"

chr: 22

healthydir: "/mnt/projects/huangwt/wgs/hanae/data/initialsamples/initialsamples_chr22/initialsamples_chr22_CRC-123_121115-CW-T"
tumordir: "/mnt/projects/huangwt/wgs/hanae/data/initialsamples/initialsamples_chr22/initialsamples_chr22_CRC-123_310715-CW-T"
buffycoatdir: "/mnt/projects/huangwt/wgs/hanae/data/initialsamples/initialsamples_chr22/initialsamples_chr22_CRC-123-CW-N"
outputfolder: "/mnt/projects/huangwt/wgs/hanae/data/mixtures/mixtures_chr22"

tffile: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/initialsamples/ctDNA_burden_estimation_deepwgs_plasma_CRC_samples.csv" 
ichorcnaextdata: "/mnt/projects/carriehc/cfDNA/anaconda3/envs/ichorcna/lib/R/library/ichorCNA/extdata/"
samtools: "/mnt/projects/skanderupamj/wgs/bcbio_v107/bin/samtools"
