############# Config file ############

normalbam: "/rfs-storageservice/GIS/Projects/LOCCG/projects/hanae-exome/bcbio/986_100215_M1-E/bcbio_final/986_100215_M1-E-N/986_100215_M1-E-N-ready.bam"
tumorbam: "/rfs-storageservice/GIS/Projects/LOCCG/projects/hanae-exome/bcbio/986_100215_M1-E/bcbio_final/986_100215_M1-E-T/986_100215_M1-E-T-ready.bam" 
includeallelefrequency: True
processesfilter: 8
processespredict: 2
outdir: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/varnet_outdir/CRC-986_100215-M1W/"
extdata: "/rfs-storageservice/GIS/Projects/LOCCG/carriehc/extdata/"
mode: "exome"
chr: "all"
condapath: "/scratch/users/astar/gis/simngl/apps/bcbio_v129/anaconda/etc/profile.d/conda.sh"
repopath: "/rfs-storageservice/GIS/Projects/LOCCG/apps/varnet_hanae/"
tooldir: "/scratch/users/astar/gis/simngl/apps/VarNet/v1"
py: "/scratch/users/astar/gis/simngl/apps/bcbio_v129/anaconda/envs/varnet/bin/python"
picard: "/rfs-storageservice/GIS/Projects/LOCCG/apps/bcbio/v129/anaconda/envs/java/share/picard-2.27.4-0/picard.jar"
java: "/rfs-storageservice/GIS/Projects/LOCCG/apps/bcbio/v129/anaconda/bin/java"
samtools: "/rfs-storageservice/GIS/Projects/LOCCG/apps/bcbio/v129/anaconda/bin/samtools"


