##### Config file #####

inputsample:
  bamfile: "/mnt/projects/skanderupamj/wgs/data/cfdna.crc/NCC_CRC-986_300316-CW/bcbio_work/align/NCC_CRC-986_300316-CW-T/NCC_CRC-986_300316-CW-T-sort.bam"
  dsfile: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/dilutions_series_chr22/NCC_CRC-986_300316-CW-T/CRC-986_300316_chr22.bam"
  name: "CRC-986_300316"

mutsbed: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/spikein/spikein_chr22/common_cancer_mutations/CRC_chr22_SNV_tf1.bed"
tfs: "1 0.2 0.15 0.1 0.05 0.025 0.01"
chr: 22
outputdir: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/data/spikein/spikein_chr22"

refgenome: "/mnt/projects/carriehc/cfDNA/data/refgenome/GRCh37/GRCh37.fa"
picardjarfile: "/mnt/projects/carriehc/cfDNA/utils/picard.jar"
aligner: mem
mindepth: 0
maxdepth: 200000

