##### Config file #####

sample:
  healthy: "/mnt/projects/skanderupamj/wgs/data/cfdna.crc/NCC_CRC-986_300316-CW/bcbio_work/align/NCC_CRC-986_300316-CW-T/NCC_CRC-986_300316-CW-T-sort.bam"
  tumor: "/mnt/projects/skanderupamj/wgs/data/training/ready.bams/cfdna/NCC_CRC-986_100215-CW-T-ready.bam"
  buffycoat: "/mnt/projects/skanderupamj/wgs/data/training/ready.bams/cfdna/NCC_CRC-986_100215-CW-N-ready.bam"

samplename:
  healthy: "CRC-986_300316"
  tumor: "CRC-986_100215"
  buffycoat: "CRC-986_100215-BC"

dilutionfactors: "70-0 70-80 50-100 30-120 20-130 10-140 5-145 70-130 70-180 70-230"

chr: 22

healthydir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/dilutions_series/dilutions_series_chr22/NCC_CRC-986_300316-CW-T"
tumordir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/dilutions_series/dilutions_series_chr22/NCC_CRC-986_100215-CW-T"
buffycoatdir: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/dilutions_series/dilutions_series_chr22/NCC_CRC-986_100215-CW-N"
outputfolder: "/mnt/projects/zhug/cfDNA/skandlab-public/carriehc/dilutions_series/dilutions_series_chr22"

tffile: "/mnt/projects/carriehc/cfDNA/cfdna_snv/cfdna_snv_benchmark/dilutions/ctDNA_burden_estimation_deepwgs_plasma_CRC_samples.csv"
