## Params ###

outputdir: "/output/cfsnv_outdir/dilution_chr22_CRC-986_100215/dilution_chr22_CRC-986_100215_0.125_CRC-986_300316_0.875"
tmpdir: '/home/ubuntu/anaconda3/envs/cfSNV/lib/R/library/cfSNV/extdata/tmp'

plasma:
        id: 'dilution_chr22_CRC-986_100215_0.125_CRC-986_300316_0.875'
        fastq1: '/output/dilutions_chr22/dilutions_CRC-986_100215/dilution_chr22_CRC-986_100215_0.125_CRC-986_300316_0.875/dilution_chr22_CRC-986_100215_0.125_CRC-986_300316_0.875.sorted_R1.fastq.gz'
        fastq2: '/output/dilutions_chr22/dilutions_CRC-986_100215/dilution_chr22_CRC-986_100215_0.125_CRC-986_300316_0.875/dilution_chr22_CRC-986_100215_0.125_CRC-986_300316_0.875.sorted_R2.fastq.gz'
        bam: '/output/dilutions_chr22/dilutions_CRC-986_100215/dilution_chr22_CRC-986_100215_0.125_CRC-986_300316_0.875/dilution_chr22_CRC-986_100215_0.125_CRC-986_300316_0.875.sorted.bam'

normal:
        id: 'CRC-986_100215-BC_chr22'
        fastq1: '/output/dilutions_chr22/NCC_CRC-986_100215-CW-N/CRC-986_100215-BC_chr22_R1.fastq.gz'
        fastq2: '/output/dilutions_chr22/NCC_CRC-986_100215-CW-N/CRC-986_100215-BC_chr22_R2.fastq.gz'
        bam: '/output/dilutions_chr22/NCC_CRC-986_100215-CW-N/CRC-986_100215-BC_chr22.bam'

chr: 22
targetbeddir: '/output/extdata/wholegenome_bed'
reference: '/output/extdata/GRCh37/GRCh37.fa'
SNPdatabase:  '/output/extdata/dbsnp_vcf/dbSNP_hg19_chr22.vcf'

dir:
        samtools: "/home/ubuntu/anaconda3/envs/cfSNV/bin/samtools"
        picard: "/home/ubuntu/anaconda3/envs/cfSNV/share/picard-2.26.10-0/picard.jar"
        bedtools: "/home/ubuntu/anaconda3/envs/cfSNV/bin/bedtools"
        GATK: "/home/ubuntu/anaconda3/envs/cfSNV/opt/gatk-3.8/GenomeAnalysisTK.jar"
        bwa: "/home/ubuntu/anaconda3/envs/cfSNV/bin/bwa"
        flash: "/home/ubuntu/anaconda3/envs/cfSNV/bin/flash2"
        python: "/home/ubuntu/anaconda3/envs/cfSNV/bin/python"
        java: 'java'


